domain: "###ZARF_VAR_DOMAIN###"
sso:
  enabled: true
  clientId: uds-core-sonarqube
  saml:
    providerName: Keycloak # This is displayed on the login screen ("Log in with <providerName>")
    user:
      login: login
      name: name
      email: email
