image:
  repository: registry1.dso.mil/ironbank/sonarsource/sonarqube/sonarqube
  tag: 10.6.0-community

initContainers:
  image: registry1.dso.mil/ironbank/big-bang/base:2.1.0

prometheusExporter:
  image: registry1.dso.mil/ironbank/big-bang/base:2.1.0
