{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sonarqube-metrics
  namespace: {{ .Release.Namespace }}
spec:
  scrapeClass: istio-certs
  namespaceSelector:
    matchNames:
    - sonarqube
  podMetricsEndpoints:
  - path: /api/monitoring/metrics
    port: http
    scheme: https
    enableHttp2: false
    bearerTokenSecret:
      name: sonarqube-monitoring
      key: passcode
  selector:
    matchLabels:
      app: sonarqube
{{- end }}
