apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: sonarqube-sso
  namespace: {{ .Release.Namespace }}
spec:
  sso:
    - name: Sonarqube Client
      clientId: sonarqube
      redirectUris:
        - "https://sonarqube.uds.dev/oauth2/callback/saml"
      protocol: saml
      defaultClientScopes: []
      attributes:
        saml.client.signature: "false"
      protocolMappers:
        - name: "Name"
          protocol: "saml"
          protocolMapper: "saml-user-property-mapper"
          config:
            user.attribute: "Username"
            attribute.nameformat: "Basic"
            attribute.name: "name"
        - name: "Email"
          protocol: "saml"
          protocolMapper: "saml-user-property-mapper"
          config:
            user.attribute: "Email"
            attribute.nameformat: "Basic"
            attribute.name: "email"
        - name: "Login"
          protocol: "saml"
          protocolMapper: "saml-user-property-mapper"
          config:
            user.attribute: "Username"
            attribute.nameformat: "Basic"
            attribute.name: "login"

      secretName: sonarqube-sso
      secretTemplate:
        secret.properties: |
            sonar.auth.saml.certificate.secured: clientField(samlCertificate)
