# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Release

on:
  push:
    branches:
      - main

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: read # Allows reading the content of the repository.
  packages: read # Allows reading the content of the repository's packages.
  id-token: write

jobs:
  publish:
    permissions:
      contents: write # Allows reading the content of the repository.
      packages: write # Allows reading the content of the repository's packages.
      id-token: write
    needs: tag-new-version
    if: ${{ needs.tag-new-version.outputs.release_created == 'true' }}
    strategy:
      matrix:
        flavor: [upstream, registry1, unicorn]
        architecture: [amd64, arm64]
        exclude:
          - flavor: registry1
            architecture: arm64
    uses: defenseunicorns/uds-common/.github/workflows/callable-publish.yaml@5906378f1fad07bba927dc953c4bf42602e1b6da # v1.5.1
    with:
      flavor: ${{ matrix.flavor }}
      runsOn: ${{ matrix.architecture == 'arm64' && 'uds-swf-ubuntu-arm64-8-core' || 'uds-swf-ubuntu-big-boy-8-core' }}
      reports-path: "tests/.playwright/reports/"
      uds-releaser: true
    secrets: inherit # Inherits all secrets from the parent workflow.
